import os
import shutil
import random
from sys import argv

def split_dataset(source_images_dir, source_labels_dir, output_dir="dataset", split_ratio=0.8):
    """
    Splits images and labels into train/val sets and moves them into standard YOLO structure.
    
    Structure created:
    dataset/
      images/
        train/
        val/
      labels/
        train/
        val/
    """
    
    # 1. specific extensions to look for
    valid_extensions = {'.jpg', '.jpeg', '.png', '.bmp'}

    # 2. Create destination directories
    dirs_to_create = [
        os.path.join(output_dir, "train", "images"),
        os.path.join(output_dir, "val", "images"),
        os.path.join(output_dir, "train", "labels"),
        os.path.join(output_dir, "val", "labels")
    ]
    
    for directory in dirs_to_create:
        os.makedirs(directory, exist_ok=True)
    
    # 3. Get list of all images
    # We only take images that have a corresponding label file
    files_to_move = []
    
    if not os.path.exists(source_images_dir):
        print(f"Error: Image directory '{source_images_dir}' not found.")
        return

    print(f"Scanning '{source_images_dir}' for images...")
    
    all_files = os.listdir(source_images_dir)
    
    for filename in all_files:
        name, ext = os.path.splitext(filename)
        
        if ext.lower() not in valid_extensions:
            continue
            
        # Check if corresponding label exists
        label_file = f"{name}.txt"
        label_path = os.path.join(source_labels_dir, label_file)
        
        if os.path.exists(label_path):
            files_to_move.append({
                "base_name": name,
                "img_ext": ext,
                "label_file": label_file
            })
        else:
            shutil.move(os.path.join(source_images_dir, filename), os.path.join(output_dir, "train", "images", filename))
            print(f"Warning: Skipping {filename} (no label found in {source_labels_dir})")

    # 4. Shuffle and Split
    random.shuffle(files_to_move)
    
    split_index = int(len(files_to_move) * split_ratio)
    train_files = files_to_move[:split_index]
    val_files = files_to_move[split_index:]
    
    print(f"Found {len(files_to_move)} valid pairs.")
    print(f"Moving {len(train_files)} to Train and {len(val_files)} to Val...")

    # 5. Move files function
    def move_files(file_list, subset):
        for item in file_list:
            # Source paths
            src_img = os.path.join(source_images_dir, item["base_name"] + item["img_ext"])
            src_lbl = os.path.join(source_labels_dir, item["label_file"])
            
            # Destination paths
            dst_img = os.path.join(output_dir, subset, "images", item["base_name"] + item["img_ext"])
            dst_lbl = os.path.join(output_dir, subset, "labels", item["label_file"])
            
            # Move files (Change to shutil.copy if you want to keep originals)
            shutil.move(src_img, dst_img)
            shutil.move(src_lbl, dst_lbl)

    move_files(train_files, "train")
    move_files(val_files, "val")

    print("Done! Dataset is ready.")
    print(f"Location: {os.path.abspath(output_dir)}")

if __name__ == "__main__":
    # --- CONFIGURATION ---
    base_path = argv[1]
    output_path = argv[2]

    # Folder containing your raw images
    images_path = base_path+"/images" 

    # Folder containing the .txt labels (generated by the previous script)
    labels_path = base_path+"/labels"

    # Check if folders exist before running
    if os.path.exists(images_path) and os.path.exists(labels_path):
        split_dataset(images_path, labels_path,output_dir=output_path)
    else:
        print("Please ensure you have 'images' and 'labels' folders in this directory.")
        print(f"Looking for: {images_path} and {labels_path}")