import os
import shutil
import random
from sys import argv

def split_dataset(source_labels_dir, output_dir="dataset", split_ratio=0.8):
    """
    Splits images and labels into train/val sets and moves them into standard YOLO structure.
    
    Structure created:
    dataset/
      images/
        train/
        val/
      labels/
        train/
        val/
    """
    

    # 2. Create destination directories
    dirs_to_create = [
        os.path.join(output_dir, "train", "labels"),
        os.path.join(output_dir, "val", "labels")
    ]
    
    for directory in dirs_to_create:
        os.makedirs(directory, exist_ok=True)
    
    # 3. Get list of all images
    # We only take images that have a corresponding label file
    files_to_move = []
    
    if not os.path.exists(source_labels_dir):
        print(f"Error: Labels directory '{source_labels_dir}' not found.")
        return

    print(f"Scanning '{source_labels_dir}' for labels...")
    
    all_files = os.listdir(source_labels_dir)
    
    # 4. Shuffle and Split
    random.shuffle(all_files)
    
    split_index = int(len(all_files) * split_ratio)
    train_files = all_files[:split_index]
    val_files = all_files[split_index:]
    
    print(f"Found {len(all_files)} valid label.")
    print(f"Moving {len(train_files)} to Train and {len(val_files)} to Val...")

    # 5. Move files function
    def move_files(file_list, subset):
        for item in file_list:
            # Source paths
            src_lbl = os.path.join(source_labels_dir, item["label_file"])
            
            # Destination paths
            dst_lbl = os.path.join(output_dir, subset, "labels", item["label_file"])
            
            # Move files (Change to shutil.copy if you want to keep originals)
            shutil.move(src_lbl, dst_lbl)

    move_files(train_files, "train")
    move_files(val_files, "val")

    print("Done! Dataset is ready.")
    print(f"Location: {os.path.abspath(output_dir)}")

if __name__ == "__main__":
    # --- CONFIGURATION ---
    base_path = argv[1]
    output_path = argv[2]

    # Folder containing the .txt labels (generated by the previous script)
    labels_path = base_path+"/labels"

    # Check if folders exist before running
    if os.path.exists(labels_path):
        split_dataset(labels_path,output_dir=output_path)
    else:
        print("Please ensure you have 'images' and 'labels' folders in this directory.")
        print(f"Looking for: {labels_path}")